# 키보드 자판
Keyboard=Dubeolsik
# 한자 모드 변환 키
HanjaModeToggleKey=
# 이전 페이지
PrevPage=
# 다음 페이지
NextPage=
# 이전 후보
PrevCandidate=
# 다음 후보
NextCandidate=
# 자동 재배열
AutoReorder=False
# 단어 단위 입력
WordCommit=False
# 한자 모드
HanjaMode=False

