local nvim_set_hl = vim.api.nvim_set_hl
-- nvim_set_hl(0, "Normal", { fg = "#C9C9C9" })
-- nvim_set_hl(0, "NonText", { fg = "#4A4A4A" })
-- nvim_set_hl(0, "Comment", { fg = "#666967" })
-- nvim_set_hl(0, "Constant", { fg = "#88766F" })
-- nvim_set_hl(0, "String", { fg = "#94BACA" })
-- nvim_set_hl(0, "Identifier", { fg = "#96A8A1" })
-- nvim_set_hl(0, "Statement", { fg = "#998B70" })
-- nvim_set_hl(0, "Exception", { fg = "#A74F4F" })
-- nvim_set_hl(0, "Keyword", { fg = "#858CA6" })
-- nvim_set_hl(0, "Operator", { fg = "#C9C9C9" })
-- nvim_set_hl(0, "PreProc", { fg = "#88766F" })
-- nvim_set_hl(0, "Include", { fg = "#88766F" })
-- nvim_set_hl(0, "Macro", { fg = "#88766F" })
-- nvim_set_hl(0, "Define", { fg = "#998B70" })
-- nvim_set_hl(0, "Type", { fg = "#858CA6" })
-- nvim_set_hl(0, "Special", { fg = "#666967" })
-- nvim_set_hl(0, "Error", { bg = "NONE", fg = "#A74F4F", bold = true })
-- nvim_set_hl(0, "Warning", { bg = "NONE", fg = "#EAB56B", bold = true })
-- nvim_set_hl(0, "ModeMsg", { bg = "NONE", fg = "#94BACA" })
-- nvim_set_hl(0, "Todo", { bg = "NONE", fg = "#679D80", bold = true })
-- nvim_set_hl(0, "Underlined", { bg = "NONE", fg = "#C9C9C9", underline = true })
nvim_set_hl(0, "StatusLine", { bg = "#000000", fg = "#5a5a5a", italic = true })
nvim_set_hl(0, "StatusLineNC", { bg = "#000000", fg = "#666967", italic = true })
-- nvim_set_hl(0, "Title", { bg = "NONE", fg = "#998B70", bold = true })
-- nvim_set_hl(0, "LineNr", { bg = "NONE", fg = "#666967" })
-- nvim_set_hl(0, "CursorLineNr", { bg = "#2A2A2A", fg = "#EAB56B" })
-- nvim_set_hl(0, "Cursor", { bg = "#C9C9C9", fg = "#222222" })
-- nvim_set_hl(0, "CursorLine", { bg = "#2A2A2A", fg = "NONE" })
-- nvim_set_hl(0, "ColorColumn", { bg = "#1A1A1A", fg = "NONE" })
-- nvim_set_hl(0, "SignColumn", { bg = "NONE", fg = "#666967" })

vim.defer_fn(function()
    -- gitsigns.nvim
    nvim_set_hl(0, "GitSignsAdd", { bg = "NONE", fg = "green" })
    nvim_set_hl(0, "GitSignsChange", { bg = "NONE", fg = "blue" })
    nvim_set_hl(0, "GitSignsDelete", { bg = "NONE", fg = "red" })
    nvim_set_hl(0, "GitSignsChange", { bg = "NONE", fg = "yellow" })

    -- nvim_set_hl(0, "Conceal", { bg = "NONE", fg = "#C9C9C9" })
    -- nvim_set_hl(0, "VertSplit", { bg = "NONE", fg = "#2e2e2e" })
    -- nvim_set_hl(0, "WildMenu", { bg = "#2A2A2A", fg = "#EAB56B", italic = true })
    -- nvim_set_hl(0, "Visual", { bg = "#343434", fg = "NONE" })
    -- nvim_set_hl(0, "VisualNOS", { bg = "#343434", fg = "NONE" })
    -- nvim_set_hl(0, "Pmenu", { bg = "#2A2A2A", fg = "NONE" })
    -- nvim_set_hl(0, "PmenuSbar", { bg = "#343434", fg = "NONE" })
    -- nvim_set_hl(0, "PmenuSel", { bg = "#343434", fg = "#998B70" })
    -- nvim_set_hl(0, "PmenuThumb", { bg = "#94BACA", fg = "NONE" })
    -- nvim_set_hl(0, "FoldColumn", { bg = "NONE", fg = "#2A2A2A" })
    -- nvim_set_hl(0, "Folded", { bg = "#1A1A1A", fg = "#666967" })
    -- nvim_set_hl(0, "SpecialKey", { bg = "NONE", fg = "#998B70" })
    -- nvim_set_hl(0, "IncSearch", { bg = "#EAB56B", fg = "#222222" })
    -- nvim_set_hl(0, "Search", { bg = "#998B70", fg = "#222222" })
    -- nvim_set_hl(0, "Directory", { bg = "NONE", fg = "#94BACA" })
    -- nvim_set_hl(0, "MatchParen", { bg = "NONE", fg = "#EAB56B", bold = true })
    -- nvim_set_hl(0, "SpellBad", { bg = "NONE", fg = "#A74F4F", underline = true })
    -- nvim_set_hl(0, "SpellCap", { bg = "NONE", fg = "#679D80", underline = true })
    -- nvim_set_hl(0, "SpellLocal", { bg = "NONE", fg = "#EAB56B", underline = true })
    -- nvim_set_hl(0, "QuickFixLine", { bg = "#1A1A1A", fg = "NONE" })
    -- nvim_set_hl(0, "DiffAdd", { bg = "#2A2A2A", fg = "#679D80" })
    -- nvim_set_hl(0, "DiffChange", { bg = "#2A2A2A", fg = "NONE" })
    -- nvim_set_hl(0, "DiffDelete", { bg = "#2A2A2A", fg = "#A74F4F" })
    -- nvim_set_hl(0, "DiffText", { bg = "#2A2A2A", fg = "#EAB56B" })
    -- nvim_set_hl(0, "helpHyperTextJump", { fg = "#94BACA" })
    --
    -- nvim_set_hl(0, "DiagnosticError", { italic = true })
    -- nvim_set_hl(0, "DiagnosticWarn",  { italic = true })
    -- nvim_set_hl(0, "DiagnosticInfo",  { italic = true })
    -- nvim_set_hl(0, "DiagnosticHint",  { italic = true })
    -- nvim_set_hl(0, "DiagnosticUnderlineError", { italic = true })
    -- nvim_set_hl(0, "DiagnosticUnderlineWarn", { italic = true })
    -- nvim_set_hl(0, "DiagnosticUnderlineInfo", { italic = true })
    -- nvim_set_hl(0, "DiagnosticUnderlineHint", { italic = true })
    nvim_set_hl(0, "DiagnosticVirtualTextError", { italic = true, fg = "#65737e" })
    nvim_set_hl(0, "DiagnosticVirtualTextWarn", { italic = true, fg = "#65737e" })
    nvim_set_hl(0, "DiagnosticVirtualTextInfo", { italic = true, fg = "#65737e" })
    nvim_set_hl(0, "DiagnosticVirtualTextHint", { italic = true, fg = "#65737e" })
    -- nvim_set_hl(0, "DiagnosticFloatingError", { italic = true })
    -- nvim_set_hl(0, "DiagnosticFloatingWarn", { italic = true })
    -- nvim_set_hl(0, "DiagnosticFloatingInfo", { italic = true })
    -- nvim_set_hl(0, "DiagnosticFloatingHint", { italic = true })
    -- nvim_set_hl(0, "DiagnosticSignError", { italic = true })
    -- nvim_set_hl(0, "DiagnosticSignWarn", { italic = true })
    -- nvim_set_hl(0, "DiagnosticSignInfo", { italic = true })
    -- nvim_set_hl(0, "DiagnosticSignHint", { italic = true })
    -- nvim_set_hl(0, "MsgArea", { italic = true })

    -- nvim-cmp
    nvim_set_hl(0, "CmpItemAbbrDeprecated", { bg = "NONE", strikethrough = true, fg = "#808080" })
    nvim_set_hl(0, "CmpItemAbbrMatch", { bg = "NONE", fg = "#569CD6" })
    nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { bg = "NONE", fg = "#569CD6" })
    nvim_set_hl(0, "CmpItemKindVariable", { bg = "NONE", fg = "#9CDCFE" })
    nvim_set_hl(0, "CmpItemKindInterface", { bg = "NONE", fg = "#9CDCFE" })
    nvim_set_hl(0, "CmpItemKindText", { bg = "NONE", fg = "#9CDCFE" })
    nvim_set_hl(0, "CmpItemKindFunction", { bg = "NONE", fg = "#C586C0" })
    nvim_set_hl(0, "CmpItemKindMethod", { bg = "NONE", fg = "#C586C0" })
    nvim_set_hl(0, "CmpItemKindKeyword", { bg = "NONE", fg = "#D4D4D4" })
    nvim_set_hl(0, "CmpItemKindProperty", { bg = "NONE", fg = "#D4D4D4" })
    nvim_set_hl(0, "CmpItemKindUnit", { bg = "NONE", fg = "#D4D4D4" })
end, 10)

-- nvim_set_hl(0,  "Normal", {   background = 1184017,   foreground = 13815759 } )
nvim_set_hl(0, "Normal", { foreground = 13815759 })
nvim_set_hl(0, "Comment", { foreground = 7893617, italic = true })
nvim_set_hl(0, "ColorColumn", { background = 1512982 })
nvim_set_hl(0, "Cursor", { background = 16074310, foreground = 1184017 })
nvim_set_hl(0, "CursorI", { background = 16777215 })
nvim_set_hl(0, "CursorR", { background = 16100422 })
nvim_set_hl(0, "CursorO", { background = 4635637 })
nvim_set_hl(0, "CursorLine", { background = 2236448 })
nvim_set_hl(0, "DiffAdd", { foreground = 8956535 })
nvim_set_hl(0, "DiffChange", { foreground = 7833770 })
nvim_set_hl(0, "DiffDelete", { foreground = 11171686 })
nvim_set_hl(0, "DiffText", { foreground = 7833770, underline = true })
nvim_set_hl(0, "EndOfBuffer", { foreground = 7483440 })
nvim_set_hl(0, "Error", { bold = true, foreground = 16074310 })
nvim_set_hl(0, "ErrorMsg", { bold = true, foreground = 16074310 })
nvim_set_hl(0, "VertSplit", { foreground = 6183257 })
nvim_set_hl(0, "Folded", { background = 2236448, foreground = 13815759, italic = true })
nvim_set_hl(0, "IncSearch", { background = 16100422, bold = true, foreground = 1184017, reverse = true })
nvim_set_hl(0, "Substitute", { background = 16100422, bold = true, foreground = 1184017 })
nvim_set_hl(0, "LineNr", { foreground = 6183257 })
nvim_set_hl(0, "CursorLineNr", { background = 2236448, foreground = 10262165 })
nvim_set_hl(0, "MatchParen", { background = 16100422, foreground = 1184017 })
nvim_set_hl(0, "ParenMatch", { background = 16100422, foreground = 1184017 })
nvim_set_hl(0, "ModeMsg", { bold = true })
nvim_set_hl(0, "MsgSeparator", { foreground = 10262165, underline = true })
nvim_set_hl(0, "MoreMsg", { bold = true, foreground = 4635637 })
nvim_set_hl(0, "NonText", { foreground = 10177082 })
nvim_set_hl(0, "NormalFloat", { background = 1512982, foreground = 7893617 })
nvim_set_hl(0, "Pmenu", { background = 1512982, foreground = 7893617 })
nvim_set_hl(0, "PmenuSel", { background = 10262165, foreground = 1512982 })
nvim_set_hl(0, "PmenuSbar", { background = 1512982 })
nvim_set_hl(0, "PmenuThumb", { background = 3749430 })
nvim_set_hl(0, "QuickFixLine", { background = 3355443 })
nvim_set_hl(0, "Search", { background = 16100422, bold = true, foreground = 1184017 })
nvim_set_hl(0, "SpecialKey", { bold = true })
nvim_set_hl(0, "SpellBad", { special = 16729156, undercurl = true })
nvim_set_hl(0, "SpellCap", { special = 16729156, undercurl = true })
nvim_set_hl(0, "SpellLocal", { special = 14522658, undercurl = true })
nvim_set_hl(0, "SpellRare", { special = 16729156, undercurl = true })
nvim_set_hl(0, "TabLine", { foreground = 6183257 })
nvim_set_hl(0, "TabLineFill", { foreground = 6183257 })
nvim_set_hl(0, "TabLineSel", { bold = true, foreground = 10262165 })
nvim_set_hl(0, "Title", { bold = true })
nvim_set_hl(0, "Visual", { background = 13815759, foreground = 1184017 })
nvim_set_hl(0, "Warning", { foreground = 16100422 })
nvim_set_hl(0, "WarningMsg", { bold = true, foreground = 16100422 })
nvim_set_hl(0, "Whitespace", { foreground = 3749430 })
nvim_set_hl(0, "WildMenu", { background = 13815759, foreground = 1184017 })
nvim_set_hl(0, "String", { foreground = 10262165 })
nvim_set_hl(0, "Identifier", { italic = true })
nvim_set_hl(0, "Function", { italic = true })
nvim_set_hl(0, "Statement", { bold = true })
nvim_set_hl(0, "Conditional", { bold = true })
nvim_set_hl(0, "Repeat", { bold = true })
nvim_set_hl(0, "Label", { bold = true })
nvim_set_hl(0, "Operator", { bold = true })
nvim_set_hl(0, "Keyword", { bold = true })
nvim_set_hl(0, "Exception", { bold = true })
nvim_set_hl(0, "Include", { italic = true })
nvim_set_hl(0, "Type", { bold = true })
nvim_set_hl(0, "StorageClass", { bold = true })
nvim_set_hl(0, "Structure", { bold = true })
nvim_set_hl(0, "Typedef", { bold = true })
nvim_set_hl(0, "Underlined", { underline = true })
nvim_set_hl(0, "Todo", { bold = true, foreground = 16100422, italic = true })
