FROM alpine:edge
RUN apk add --no-cache python2 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.15/community
# RUN apk add --no-cache py2-pip --repository=http://dl-cdn.alpinelinux.org/alpine/v3.11/main
RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN echo "@community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk add --no-cache \
      fd@community \
      tree-sitter@community \
      neovim@community \
RUN apk add --no-cache --force-overwrite \
      ca-certificates \
      curl \
      stow \
      fzf \
      vifm \
      ripgrep \
      bash

# stow
RUN git clone --recurse-submodules -j20 https://github.com/aca/dotfiles ~/src/config/dotfiles --depth 1 && rm -rf ~/src/config/dotfiles/.git
RUN bash ~/src/config/dotfiles/.bin/setup.stow

RUN nvim --headless -c ':packadd nvim-treesitter' -c ':TSInstallSync! bash c cpp css go html javascript lua make markdown python tsx typescript yaml' -c ':q'
# RUN nvim --headless -c ':LspInstall --sync gopls' -c ':q'

CMD ["/usr/local/bin/bash"]
