ARG BASE_IMAGE=acadx0/tools:devcontainer-base
FROM $BASE_IMAGE

WORKDIR /root
RUN git clone -j 8 "https://gitlab.com/acadx0/dotfiles.git" ~/src/root/dotfiles --recursive --shallow-submodules && rm -rf ~/src/root/dotfiles/.git
RUN git clone "https://github.com/aca/stow-antifold.git" ~/src/root/stow-antifold
RUN sh -c "cd ~/src/root && stow --adopt -v --target $HOME dotfiles stow-antifold"
