-- $ vim-startuptime -vimpath nvim | grep '^Total'
--
-- Total Average: 5.900700 msec
-- Total Max:     6.221000 msec
-- Total Min:     5.663000 msec
--
-- TODO
-- https://github.com/adelarsq/image_preview.nvim
-- https://www.reddit.com/r/neovim/comments/y9mg1t/smartest_autopair_plugin_nowadays/
