#!/usr/bin/env sh
#
# @file mpvc-cut
# @description mpvc cuts playing media between ab-loop points (idea from lwillets)
# @author gmt4 <gmt4 at github.com> (c) Copyright 2022 GPLv2+
# @url github.com/gmt4/mpvc
# SPDX-License-Identifier: GPL-2.0-or-later
#

PROGNAME=${0##*/}
PROGVERSION="v1.8"
PROGAUTHOR=gmt4
PROGURL="https://github.com/gmt4/mpvc"

set -euf

PACTL=$(command -v pactl) || { echo "pactl not found"; exit 1; }
FFMPEG=$(command -v ffmpeg) || { echo "ffmpeg not found"; exit 1; }
FFPROBE=$(command -v ffprobe) || { echo "ffprobe not found"; exit 1; }

mpvc_cut_ffmpeg()
{
    "$FFMPEG" -hide_banner -loglevel "$LOGLEVEL" -i "$path" -ss "$pointA" -to "$pointB" -- "$@"
}

mpvc_cutfile()
{
    operation="$1"
    path="$2"
    pointA="$3"
    pointB="$4"

    if [ -z "$path" ] || [ ! -f "$path" ]; then usage 1; fi
    if [ -z "$pointA" ] || [ "$pointA" = "no" ]; then usage 1; fi
    if [ -z "$pointB" ] || [ "$pointB" = "no" ]; then pointB="$(mpvc -f "%length%")"; fi

    fileExt="${path#*.}"
    infile="${path##*/}"
    infile="${infile##"$fileExt"}"
    outfile="${outfile:-${infile}_${pointA}_${pointB}}"
    LOGLEVEL=${LOGLEVEL:-warning}

    echo "# $PROGNAME $operation $pointA $pointB $fileExt in $infile out $outfile"

    case "$operation" in
    vidcord) # perform lossy transcode to x264
        mpvc_cut_ffmpeg \
               -max_muxing_queue_size 1024 \
               -sws_flags lanczos -vf "scale=-1:720" \
               -c:v libx264 -crf 25 -preset fast \
               -c:a copy -map 0 -f mp4 "$outfile.mp4"
    ;;
    lossless) mpvc_cut_ffmpeg -c:v libx265 -x265-params lossless=1 "$outfile.mp4" ;;
    lossy)    mpvc_cut_ffmpeg "$outfile.mp4" ;;
    dryrun)   mpvc_cut_ffmpeg -f null /dev/null ;;
    *)        mpvc_cut_ffmpeg -c copy -map 0 "$outfile.$fileExt" ;;
    esac
}

mpvc_cut()
{
    mpvc_cutfile "$operation" "$(mpvc g 'path')" "$(mpvc g 'ab-loop-a')" "$(mpvc g 'ab-loop-b')"
}

mpvc_cut_vres()
{
    $(command -v xrandr) | awk '
        /^Screen 0: .* current .*/ {
            r=$0; sub("^.* current ","",r); sub(", maximum .*$","",r); gsub(" ","",r); print r; exit
        }'
}

mpvc_cut_info()
{
    mode=$1; shift
    "$FFPROBE" -hide_banner -loglevel info "$@" 2>&1 |
        case "$mode" in
        info) awk '/^Input/ {print} /Stream #/ {print} /Duration:/ {print}' ;;
        Info) awk '{print}' ;;
        meta|Meta) awk '{print}' ;;
        genre) awk '/^Input/ {print} /genre *:/ {print}' ;;
        esac
}

mpvc_cut_asrc()
{
    "$PACTL" list sources |
        awk '
        /^Source #.*/ { s=$2; sub("#","",s); }
        / *Description: Monitor of / {print s; exit }
        '
}

mpvc_screencast()
{
    vres=$(mpvc_cut_vres)
    asrc=$(mpvc_cut_asrc)

    fout="${fout:-mpvc-cast-$(date -Iseconds | sed 's/:/-/g').mkv}"
    LOGLEVEL=${LOGLEVEL:-warning}
    framerate=${framerate:-25}

    if [ -z "$vres" ]; then usage; fi
    if [ -z "$asrc" ]; then usage; fi

    echo "# $PROGNAME: recording vres $vres asrc $asrc to $fout (ctl+c to finish)"
    "$FFMPEG" -hide_banner -loglevel "$LOGLEVEL" -video_size "$vres" -framerate "$framerate" -f x11grab -i :0.0 -f pulse -ac 2 -i "$asrc" "$fout"
}

usage()
{
    cat <<EOF
usage: $PROGNAME -[acidlLvDh] args # @version $PROGVERSION (c) $PROGAUTHOR $PROGURL
 -a|asrc    : Show default pactl audio output (used as source for screencast).
 -c|cast    : Record an screencast using x11+pulse.
 -i|info    : Run ffprobe(1) on input file and report media info.

 -d|default : Cut current media between ab-loop points using defaults (copy).
 -l|lossy   : Cut current media between ab-loop points using lossy compression.
 -L|lossless: Cut current media between ab-loop points using lossless compression.
 -v|vidcord : Cut current media between ab-loop points using vidcord compression.
 -D|dryrun  : Cut current media between ab-loop points using dryrun (no action).
 -h|help    : This help
*tips: If unsure about where to begin, start with: $PROGNAME preset
EOF
    exit "${1:-0}"
}

main()
{
    #if ! mpvc -q; then usage 1; fi

    case "${1:-}" in
    -h|--help|help)          usage ;;
    -l|--lossy|lossy)        operation="lossy" mpvc_cut ;;
    -L|--lossless|lossless)  operation="lossless" mpvc_cut ;;
    -v|--vidcord|vidcord)    operation="vidcord" mpvc_cut ;;
    -d|--default|default)    operation="default" mpvc_cut ;;
    -D|--dryrun|dryrun)      operation="dryrun" mpvc_cut ;;

    -i|info)                 shift; mpvc_cut_info info "$@"; return ;;
    -I|Info)                 shift; mpvc_cut_info Info "$@"; return ;;
    -g|genre)                shift; mpvc_cut_info genre "$@"; return ;;
    -a|asrc)                 shift; mpvc_cut_asrc "$@"; return ;;
    -c|cast)                 shift; mpvc_screencast "$@" ;;
    *)                       usage ;;
    esac
}

main "$@"
