#!/bin/sh
#
# POSIX compliant command runner. Alternative to make, just, taskfile etc.
#
# @file is a file that is used to identify the root directory ($PROJECT_ROOT) of the project just like Makefile.
# 
# This command will simply execute $PROJECT_ROOT/build in the root directory
#
#   @ build
#
# TODO: implement dag with this https://benhoyt.com/writings/awk-make/ ?

rootdir() {
    current_dir="$PWD"
    while [ "$current_dir" != "/" ]; do
        if [ -f "$current_dir/@file" ]; then
            echo "$current_dir"
            exit 0
        fi
        current_dir=$(dirname "$current_dir")
    done
    exit 1
}

ROOT_DIR=$(rootdir @file)
cd $ROOT_DIR

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "No argument provided. Please provide an argument."
    exit 1
fi

command="$1"
shift
args="$@"

./@/$command "$@"
exit 0
