#!/bin/sh
#
# Command runner. Alternative to make, just, taskfile etc.
#
# - POSIX compliant, run on anywhere.
# - Run in any directory under the project
#
# @file is a file that is used to identify the root directory ($PROJECT_ROOT) of the project just like Makefile.
# This command will simply execute $PROJECT_ROOT/@/build in the root directory.
#
#   @ build
#
# TODO: implement dag with this https://benhoyt.com/writings/awk-make/ ?

if [ $# -eq 0 ]; then
    echo 'Usage: @ <command>'
    exit 0
fi

case $1 in
    -i) 
        touch "@file"
        mkdir -p "@"
        echo "@ initalized in "$PWD
        exit
        ;;
esac
rootdir() {
    current_dir="$PWD"
    while [ "$current_dir" != "/" ]; do
        if [ -f "$current_dir/@file" ]; then
            echo "$current_dir"
            exit 0
        fi
        current_dir=$(dirname "$current_dir")
    done
    exit 1
}

ROOT_DIR=$(rootdir @file)
cd $ROOT_DIR

command="$1"
shift
args="$@"

./@/$command "$@"
