#!/usr/bin/env bash
set -euxo pipefail

cd /tmp

export GO111MODULE=on 

GO111MODULE=on go get golang.org/x/tools/gopls@latest
GO111MODULE=on go get mvdan.cc/gofumpt
GO111MODULE=on go get mvdan.cc/gofumpt/gofumports
GO111MODULE=on go get mvdan.cc/xurls/v2/cmd/xurls
# GO111MODULE=on go get github.com/tmccombs/hcl2json

go get -u go101.org/golds/godoge
go get -u go101.org/golds/gocore
go get -u go101.org/golds/gold

# libraries
GO111MODULE=off go get -u github.com/sanity-io/litter
