#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    physlock
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # pmset displaysleepnow
    osascript -e 'tell application "System Events" to keystroke "q" using {command down,control down}' fi
fi
