#!/usr/bin/env bash

p = "$(pwd)"

if command docker ps 1>/dev/null 2>/dev/null; then
  docker container run --interactive --rm --volume "$p:$p:ro" lspcontainers/lua-language-server:1.20.5
else
  sleep 100000
fi


