#!/usr/bin/env fish

# merge A B
# like rsync A/ B/
# but without copying

set SRC "$argv[1]"
set DST "$argv[2]"

# mkdir subdirectory
for d in (fd . --type d "$SRC" | string replace "$SRC" "$DST")
  mkdir -v $d || true
end

# mv file
for f in (fd . --type f "$SRC")
  set -l newf (string replace "$SRC" "$DST" "$f")
  mv -nv "$f" "$newf"
end

# mv file if same
for f in (fd . --type f "$SRC")
  set newf (string replace "$SRC" "$DST" "$f")
  diff "$f" "$newf" && mv -v "$f" "$newf"
end



