#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # sudo netstat -tulanp
  sudo ss --listening --tcp --numeric
elif [[ "$OSTYPE" == "darwin"* ]]; then
  sudo lsof -iTCP -sTCP:LISTEN -n -P
fi

