#!/usr/bin/env bash
# 
# cleanup completed torrents(without deleting files)
# https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation
set -euxo pipefail

tmpf=$(mktemp)

host="http://localhost:4321"

curl --fail -b $tmpf -c $tmpf "http://localhost:4321/api/v2/auth/login" --data 'username=admin&password=adminadmin'
opt=("--cookie" "$tmpf" "--cookie-jar" "$tmpf" "--fail")

# curl ${opt[@]} -s "$host/api/v2/torrents/info" | jq -r '.[] | select (.completion_on != -32400 ) | select (.magnet_uri | contains ("ab.site") | not) | .name' 
#
# curl ${opt[@]} -s "$host/api/v2/torrents/info" | jq -r '.[] | select (.completion_on != -32400 ) | select (.magnet_uri | contains ("ab.site") | not) | .hash' | xargs -I{} curl ${opt[@]} -vvv -X POST "$host/api/v2/torrents/recheck?hashes={}"

curl ${opt[@]} -s "$host/api/v2/torrents/info" | jq -r '.[] | select (.completion_on != -32400 ) | select (.magnet_uri | contains ("ab.site") | not) | .hash' | xargs -I{} curl ${opt[@]} -vvv --data "hashes={}&deleteFiles=false" "$host/api/v2/torrents/delete"

# /api/v2/torrents/recheck?hashes={}

