#!/bin/sh

SCRATCH_DIR=${SCRATCH_DIR:-$HOME/src/scratch}
mkdir $SCRATCH_DIR 2>/dev/null || true

if [ "$#" -eq 0 ]; then
  project_dir=$SCRATCH_DIR/$(fd --base-directory "$SCRATCH_DIR" --strip-cwd-prefix --hidden --type d --max-depth 1 --no-ignore -0 | fzf --read0)
else
  project_dir=$SCRATCH_DIR/$(date "+%Y-%m-%d")_$1
  mkdir $project_dir || true
fi

# git init
# git remote add origin https://git.aca.us.to/scratch/(basename (pwd)).git

echo $project_dir

