#!/bin/sh

# diskus --apparent-size $1 2>/dev/null | cat

uname_S=$(sh -c 'uname -s 2>/dev/null || echo not')
if [ "$uname_S" = "Darwin" ] || [ "$uname_S" = "darwin" ]; then
  stat -f "%z" "$1"
else
  stat -c "%s" "$1"
fi
