#!/usr/bin/env fish

mkdir -p ~/src/zettels/log 2>/dev/null || true

if [ (count $argv) -eq 0 ]
  $EDITOR "$HOME/src/zettels/log/"$(date '+%Y-%m-%d').md
else
  $EDITOR "$HOME/src/zettels/log/"$(date '+%Y-%m-%d')_$argv.md
end
