#!/bin/bash

cd ~/src/zk

if [ "$#" -eq 0 ]; then
  # fd --type f --exclude '/log' | fzf 
  files=$(fd --type f . | fzf --preview 'bat {}' --preview-window='right,70%')
  if [ "$files" = "" ]; then
    exit 0
  fi
  nvim -o $files
else
  nvim "$(date '+%Y%m%dT%H%M%S')_$(echo "$@" | sed 's/ /-/g').md"
fi

