#!/bin/bash

mkdir -p ~/src/zk/log 2>/dev/null || true
cd ~/src/zk/log

suffix=${1:-$(hostname)}
if [ "$suffix" = "rok-x1cg10" ]; then
  $EDITOR "$HOME/src/zk/log/"$(date '+%Y%m%dT000000').md
else
  $EDITOR "$HOME/src/zk/log/"$(date '+%Y%m%dT000000')_$suffix.md
fi
