#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  [ -z "$1" ] && echo "No argument supplied" && exit 1
    osascript << EOF
tell application "System Events"
  click ((first menu bar item where description contains "Wi" and description contains "Fi") of menu bar 1 of process "SystemUIServer")
  click menu item "$1" of menu 1 of result
end tell
EOF
else
  exit 1
fi
