[manager]
  prepend_keymap = [
    # { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
    # or use "d + u" like me
    { on = ["d", "u"], run = "plugin restore", desc = "Restore last deleted files/folders" },
    # ... Other keymaps
	{ on = ["d", "d"], run = "remove",                      desc = "Trash selected files" },

	{ on = ["c", "w"], run = "rename",                      desc = "Rename" },
  ]
