vim.api.nvim_create_user_command("GetAllhighlights", function()

	local extractHighlight = function(s)
		local m = vim.api.nvim_get_hl_by_name(s, true)
		m[true] = nil
		print("vim.api.nvim_set_hl(0, ", '"' .. s .. '",', vim.inspect(m, { newline = " " }), ")")
	end

    local arr = {}
	for k, _ in pairs(vim.api.nvim_get_hl(0, {})) do
        table.insert(arr, k)
	end

    table.sort(arr)

	for _, v in pairs(arr) do
        extractHighlight(v)
	end

	-- for k, _ in pairs(vim.api.nvim_get_hl(0, {})) do
 --        extractHighlight(k)
	-- end
end, {})


vim.api.nvim_create_user_command("ExtractHighlights", function()
	local extractHighlight = function(s)
        local status, m = pcall(vim.api.nvim_get_hl_by_name, s, true);
        if status then
            m[true] = nil
            print("vim.api.nvim_set_hl(0, ", '"' .. s .. '",', vim.inspect(m, { newline = " " }), ")")
        else
            print("-- ", s)
        end
	end

	-- extractHighlight("Normal")
	-- extractHighlight("SyntaxError")
	-- extractHighlight("SyntaxWarning")
	-- extractHighlight("SyntaxInfo")
	-- extractHighlight("SyntaxHint")
	-- extractHighlight("Comment")
	-- extractHighlight("ColorColumn")
	-- extractHighlight("Conceal")
	-- extractHighlight("Cursor")
	-- extractHighlight("CursorI")
	-- extractHighlight("CursorR")
	-- extractHighlight("CursorO")
	-- extractHighlight("CursorLine")
	-- extractHighlight("Directory")
	-- extractHighlight("DiffAdd")
	-- extractHighlight("DiffChange")
	-- extractHighlight("DiffDelete")
	-- extractHighlight("DiffText")
	-- extractHighlight("EndOfBuffer")
	-- extractHighlight("Error")
	-- extractHighlight("ErrorMsg")
	-- extractHighlight("VertSplit")
	-- extractHighlight("Folded")
	-- extractHighlight("FoldColumn")
	-- extractHighlight("SignColumn")
	-- extractHighlight("IncSearch")
	-- extractHighlight("Substitute")
	-- extractHighlight("LineNr")
	-- extractHighlight("CursorLineNr")
	-- extractHighlight("MatchParen")
	-- extractHighlight("ParenMatch")
	-- extractHighlight("ModeMsg")
	-- extractHighlight("MsgArea")
	-- extractHighlight("MsgSeparator")
	-- extractHighlight("MoreMsg")
	-- extractHighlight("NonText")
	-- extractHighlight("NormalFloat")
	-- extractHighlight("NormalNC")
	-- extractHighlight("Pmenu")
	-- extractHighlight("PmenuSel")
	-- extractHighlight("PmenuSbar")
	-- extractHighlight("PmenuThumb")
	-- extractHighlight("Question")
	-- extractHighlight("QuickFixLine")
	-- extractHighlight("Search")
	-- extractHighlight("SpecialKey")
	-- extractHighlight("SpellBad")
	-- extractHighlight("SpellCap")
	-- extractHighlight("SpellLocal")
	-- extractHighlight("SpellRare")
	-- extractHighlight("StatusLine")
	-- extractHighlight("StatusLineNC")
	-- extractHighlight("TabLine")
	-- extractHighlight("TabLineFill")
	-- extractHighlight("TabLineSel")
	-- extractHighlight("Title")
	-- extractHighlight("Visual")
	-- extractHighlight("VisualNOS")
	-- extractHighlight("Warning")
	-- extractHighlight("WarningMsg")
	-- extractHighlight("Whitespace")
	-- extractHighlight("WildMenu")
	-- extractHighlight("Constant")
	-- extractHighlight("String")
	-- extractHighlight("Character")
	-- extractHighlight("Number")
	-- extractHighlight("Boolean")
	-- extractHighlight("Float")
	-- extractHighlight("Identifier")
	-- extractHighlight("Function")
	-- extractHighlight("Statement")
	-- extractHighlight("Conditional")
	-- extractHighlight("Repeat")
	-- extractHighlight("Label")
	-- extractHighlight("Operator")
	-- extractHighlight("Keyword")
	-- extractHighlight("Exception")
	-- extractHighlight("PreProc")
	-- extractHighlight("Include")
	-- extractHighlight("Define")
	-- extractHighlight("Macro")
	-- extractHighlight("PreCondit")
	-- extractHighlight("Type")
	-- extractHighlight("StorageClass")
	-- extractHighlight("Structure")
	-- extractHighlight("Typedef")
	-- extractHighlight("Special")
	-- extractHighlight("SpecialChar")
	-- extractHighlight("Tag")
	-- extractHighlight("Delimiter")
	-- extractHighlight("SpecialComment")
	-- extractHighlight("Debug")
	-- extractHighlight("Underlined")
	-- extractHighlight("Bold")
	-- extractHighlight("Italic")
	-- extractHighlight("Todo")
	-- extractHighlight("LspReferenceText")
	-- extractHighlight("LspReferenceRead")
	-- extractHighlight("LspReferenceWrite")
	-- extractHighlight("IndentBlanklineChar")
	-- extractHighlight("IndentBlanklineContextChar")
	-- extractHighlight("DiagnosticError")
	-- extractHighlight("DiagnosticWarn")
	-- extractHighlight("DiagnosticInfo")
	-- extractHighlight("DiagnosticHint")
	-- extractHighlight("DiagnosticUnderlineError")
	-- extractHighlight("DiagnosticUnderlineWarn")
	-- extractHighlight("DiagnosticUnderlineInfo")
	-- extractHighlight("DiagnosticUnderlineHint")
	-- extractHighlight("DiagnosticSignError")
	-- extractHighlight("DiagnosticSignWarning")
	-- extractHighlight("DiagnosticSignInformation")
	-- extractHighlight("DiagnosticSignHint")
	-- extractHighlight("TSConstant")
	-- extractHighlight("TSProperty")
	-- extractHighlight("TSStringRegex")
	-- extractHighlight("TSStringEscape")

	extractHighlight("SpecialKey")
	extractHighlight("EndOfBuffer")
	extractHighlight("TermCursor")
	extractHighlight("TermCursorNC")
	extractHighlight("NonText")
	extractHighlight("Directory")
	extractHighlight("ErrorMsg")
	extractHighlight("IncSearch")
	extractHighlight("Search")
	extractHighlight("CurSearch")
	extractHighlight("MoreMsg")
	extractHighlight("ModeMsg")
	extractHighlight("LineNr")
	extractHighlight("LineNrAbove")
	extractHighlight("LineNrBelow")
	extractHighlight("CursorLineNr")
	extractHighlight("CursorLineSign")
	extractHighlight("CursorLineFold")
	extractHighlight("Question")
	extractHighlight("StatusLine")
	extractHighlight("StatusLineNC")
	extractHighlight("WinSeparator")
	extractHighlight("VertSplit")
	extractHighlight("Title")
	extractHighlight("Visual")
	extractHighlight("VisualNC")
	extractHighlight("WarningMsg")
	extractHighlight("WildMenu")
	extractHighlight("Folded")
	extractHighlight("FoldColumn")
	extractHighlight("DiffAdd")
	extractHighlight("DiffChange")
	extractHighlight("DiffDelete")
	extractHighlight("DiffText")
	extractHighlight("SignColumn")
	extractHighlight("Conceal")
	extractHighlight("SpellBad")
	extractHighlight("SpellCap")
	extractHighlight("SpellRare")
	extractHighlight("SpellLocal")
	extractHighlight("Pmenu")
	extractHighlight("PmenuSel")
	extractHighlight("PmenuSbar")
	extractHighlight("PmenuThumb")
	extractHighlight("TabLine")
	extractHighlight("TabLineSel")
	extractHighlight("TabLineFill")
	extractHighlight("CursorColumn")
	extractHighlight("CursorLine")
	extractHighlight("ColorColumn")
	extractHighlight("QuickFixLine")
	extractHighlight("Whitespace")
	extractHighlight("NormalNC")
	extractHighlight("MsgSeparator")
	extractHighlight("NormalFloat")
	extractHighlight("MsgArea")
	extractHighlight("FloatBorder")
	extractHighlight("WinBar")
	extractHighlight("WinBarNC")
	extractHighlight("Cursor")
	extractHighlight("FloatTitle")
	extractHighlight("lCursor")
	extractHighlight("Normal")
	extractHighlight("Substitute")
	extractHighlight("FloatShadow")
	extractHighlight("FloatShadowThrough")
	extractHighlight("RedrawDebugNormal")
	extractHighlight("RedrawDebugClear")
	extractHighlight("RedrawDebugComposed")
	extractHighlight("RedrawDebugRecompose")
	extractHighlight("Error")
	extractHighlight("Todo")
	extractHighlight("String")
	extractHighlight("Constant")
	extractHighlight("Character")
	extractHighlight("Number")
	extractHighlight("Boolean")
	extractHighlight("Float")
	extractHighlight("Function")
	extractHighlight("Identifier")
	extractHighlight("Conditional")
	extractHighlight("Statement")
	extractHighlight("Repeat")
	extractHighlight("Label")
	extractHighlight("Operator")
	extractHighlight("Keyword")
	extractHighlight("Exception")
	extractHighlight("Include")
	extractHighlight("PreProc")
	extractHighlight("Define")
	extractHighlight("Macro")
	extractHighlight("PreCondit")
	extractHighlight("StorageClass")
	extractHighlight("Type")
	extractHighlight("Structure")
	extractHighlight("Typedef")
	extractHighlight("Tag")
	extractHighlight("Special")
	extractHighlight("SpecialChar")
	extractHighlight("Delimiter")
	extractHighlight("SpecialComment")
	extractHighlight("Debug")
	extractHighlight("DiagnosticError")
	extractHighlight("DiagnosticWarn")
	extractHighlight("DiagnosticInfo")
	extractHighlight("DiagnosticHint")
	extractHighlight("DiagnosticOk")
	extractHighlight("DiagnosticUnderlineError")
	extractHighlight("DiagnosticUnderlineWarn")
	extractHighlight("DiagnosticUnderlineInfo")
	extractHighlight("DiagnosticUnderlineHint")
	extractHighlight("DiagnosticUnderlineOk")
	extractHighlight("DiagnosticVirtualTextError")
	extractHighlight("DiagnosticVirtualTextWarn")
	extractHighlight("DiagnosticVirtualTextInfo")
	extractHighlight("DiagnosticVirtualTextHint")
	extractHighlight("DiagnosticVirtualTextOk")
	extractHighlight("DiagnosticFloatingError")
	extractHighlight("DiagnosticFloatingWarn")
	extractHighlight("DiagnosticFloatingInfo")
	extractHighlight("DiagnosticFloatingHint")
	extractHighlight("DiagnosticFloatingOk")
	extractHighlight("DiagnosticSignError")
	extractHighlight("DiagnosticSignWarn")
	extractHighlight("DiagnosticSignInfo")
	extractHighlight("DiagnosticSignHint")
	extractHighlight("DiagnosticSignOk")
	extractHighlight("@text")
	extractHighlight("@text.literal")
	extractHighlight("Comment")
	extractHighlight("@text.reference")
	extractHighlight("@text.title")
	extractHighlight("@text.uri")
	extractHighlight("Underlined")
	extractHighlight("@text.underline")
	extractHighlight("@text.todo")
	extractHighlight("@comment")
	extractHighlight("@punctuation")
	extractHighlight("@constant")
	extractHighlight("@constant.builtin")
	extractHighlight("@constant.macro")
	extractHighlight("@define")
	extractHighlight("@macro")
	extractHighlight("@string")
	extractHighlight("@string.escape")
	extractHighlight("@string.special")
	extractHighlight("@character")
	extractHighlight("@character.special")
	extractHighlight("@number")
	extractHighlight("@boolean")
	extractHighlight("@float")
	extractHighlight("@function")
	extractHighlight("@function.builtin")
	extractHighlight("@function.macro")
	extractHighlight("@parameter")
	extractHighlight("@method")
	extractHighlight("@field")
	extractHighlight("@property")
	extractHighlight("@constructor")
	extractHighlight("@conditional")
	extractHighlight("@repeat")
	extractHighlight("@label")
	extractHighlight("@operator")
	extractHighlight("@keyword")
	extractHighlight("@exception")
	extractHighlight("@variable")
	extractHighlight("@type")
	extractHighlight("@type.definition")
	extractHighlight("@storageclass")
	extractHighlight("@namespace")
	extractHighlight("@include")
	extractHighlight("@preproc")
	extractHighlight("@debug")
	extractHighlight("@tag")
	extractHighlight("@class")
	extractHighlight("@struct")
	extractHighlight("@enum")
	extractHighlight("@enumMember")
	extractHighlight("@event")
	extractHighlight("@interface")
	extractHighlight("@modifier")
	extractHighlight("@regexp")
	extractHighlight("@typeParameter")
	extractHighlight("@decorator")
	extractHighlight("MatchParen")
	extractHighlight("Ignore")
	extractHighlight("NvimInternalError")
	extractHighlight("NvimAssignment")
	extractHighlight("NvimPlainAssignment")
	extractHighlight("NvimAugmentedAssignment")
	extractHighlight("NvimAssignmentWithAddition")
	extractHighlight("NvimAssignmentWithSubtraction")
	extractHighlight("NvimAssignmentWithConcatenation")
	extractHighlight("NvimOperator")
	extractHighlight("NvimUnaryOperator")
	extractHighlight("NvimUnaryPlus")
	extractHighlight("NvimUnaryMinus")
	extractHighlight("NvimNot")
	extractHighlight("NvimBinaryOperator")
	extractHighlight("NvimComparison")
	extractHighlight("NvimComparisonModifier")
	extractHighlight("NvimBinaryPlus")
	extractHighlight("NvimBinaryMinus")
	extractHighlight("NvimConcat")
	extractHighlight("NvimConcatOrSubscript")
	extractHighlight("NvimOr")
	extractHighlight("NvimAnd")
	extractHighlight("NvimMultiplication")
	extractHighlight("NvimDivision")
	extractHighlight("NvimMod")
	extractHighlight("NvimTernary")
	extractHighlight("NvimTernaryColon")
	extractHighlight("NvimParenthesis")
	extractHighlight("NvimLambda")
	extractHighlight("NvimNestingParenthesis")
	extractHighlight("NvimCallingParenthesis")
	extractHighlight("NvimSubscript")
	extractHighlight("NvimSubscriptBracket")
	extractHighlight("NvimSubscriptColon")
	extractHighlight("NvimCurly")
	extractHighlight("NvimContainer")
	extractHighlight("NvimDict")
	extractHighlight("NvimList")
	extractHighlight("NvimIdentifier")
	extractHighlight("NvimIdentifierScope")
	extractHighlight("NvimIdentifierScopeDelimiter")
	extractHighlight("NvimIdentifierName")
	extractHighlight("NvimIdentifierKey")
	extractHighlight("NvimColon")
	extractHighlight("NvimComma")
	extractHighlight("NvimArrow")
	extractHighlight("NvimRegister")
	extractHighlight("NvimNumber")
	extractHighlight("NvimFloat")
	extractHighlight("NvimNumberPrefix")
	extractHighlight("NvimOptionSigil")
	extractHighlight("NvimOptionName")
	extractHighlight("NvimOptionScope")
	extractHighlight("NvimOptionScopeDelimiter")
	extractHighlight("NvimEnvironmentSigil")
	extractHighlight("NvimEnvironmentName")
	extractHighlight("NvimString")
	extractHighlight("NvimStringBody")
	extractHighlight("NvimStringQuote")
	extractHighlight("NvimStringSpecial")
	extractHighlight("NvimSingleQuote")
	extractHighlight("NvimSingleQuotedBody")
	extractHighlight("NvimSingleQuotedQuote")
	extractHighlight("NvimDoubleQuote")
	extractHighlight("NvimDoubleQuotedBody")
	extractHighlight("NvimDoubleQuotedEscape")
	extractHighlight("NvimFigureBrace")
	extractHighlight("NvimSingleQuotedUnknownEscape")
	extractHighlight("NvimSpacing")
	extractHighlight("NvimInvalidSingleQuotedUnknownEscape")
	extractHighlight("NvimInvalid")
	extractHighlight("NvimInvalidAssignment")
	extractHighlight("NvimInvalidPlainAssignment")
	extractHighlight("NvimInvalidAugmentedAssignment")
	extractHighlight("NvimInvalidAssignmentWithAddition")
	extractHighlight("NvimInvalidAssignmentWithSubtraction")
	extractHighlight("NvimInvalidAssignmentWithConcatenation")
	extractHighlight("NvimInvalidOperator")
	extractHighlight("NvimInvalidUnaryOperator")
	extractHighlight("NvimInvalidUnaryPlus")
	extractHighlight("NvimInvalidUnaryMinus")
	extractHighlight("NvimInvalidNot")
	extractHighlight("NvimInvalidBinaryOperator")
	extractHighlight("NvimInvalidComparison")
	extractHighlight("NvimInvalidComparisonModifier")
	extractHighlight("NvimInvalidBinaryPlus")
	extractHighlight("NvimInvalidBinaryMinus")
	extractHighlight("NvimInvalidConcat")
	extractHighlight("NvimInvalidConcatOrSubscript")
	extractHighlight("NvimInvalidOr")
	extractHighlight("NvimInvalidAnd")
	extractHighlight("NvimInvalidMultiplication")
	extractHighlight("NvimInvalidDivision")
	extractHighlight("NvimInvalidMod")
	extractHighlight("NvimInvalidTernary")
	extractHighlight("NvimInvalidTernaryColon")
	extractHighlight("NvimInvalidDelimiter")
	extractHighlight("NvimInvalidParenthesis")
	extractHighlight("NvimInvalidLambda")
	extractHighlight("NvimInvalidNestingParenthesis")
	extractHighlight("NvimInvalidCallingParenthesis")
	extractHighlight("NvimInvalidSubscript")
	extractHighlight("NvimInvalidSubscriptBracket")
	extractHighlight("NvimInvalidSubscriptColon")
	extractHighlight("NvimInvalidCurly")
	extractHighlight("NvimInvalidContainer")
	extractHighlight("NvimInvalidDict")
	extractHighlight("NvimInvalidList")
	extractHighlight("NvimInvalidValue")
	extractHighlight("NvimInvalidIdentifier")
	extractHighlight("NvimInvalidIdentifierScope")
	extractHighlight("NvimInvalidIdentifierScopeDelimiter")
	extractHighlight("NvimInvalidIdentifierName")
	extractHighlight("NvimInvalidIdentifierKey")
	extractHighlight("NvimInvalidColon")
	extractHighlight("NvimInvalidComma")
	extractHighlight("NvimInvalidArrow")
	extractHighlight("NvimInvalidRegister")
	extractHighlight("NvimInvalidNumber")
	extractHighlight("NvimInvalidFloat")
	extractHighlight("NvimInvalidNumberPrefix")
	extractHighlight("NvimInvalidOptionSigil")
	extractHighlight("NvimInvalidOptionName")
	extractHighlight("NvimInvalidOptionScope")
	extractHighlight("NvimInvalidOptionScopeDelimiter")
	extractHighlight("NvimInvalidEnvironmentSigil")
	extractHighlight("NvimInvalidEnvironmentName")
	extractHighlight("NvimInvalidString")
	extractHighlight("NvimInvalidStringBody")
	extractHighlight("NvimInvalidStringQuote")
	extractHighlight("NvimInvalidStringSpecial")
	extractHighlight("NvimInvalidSingleQuote")
	extractHighlight("NvimInvalidSingleQuotedBody")
	extractHighlight("NvimInvalidSingleQuotedQuote")
	extractHighlight("NvimInvalidDoubleQuote")
	extractHighlight("NvimInvalidDoubleQuotedBody")
	extractHighlight("NvimInvalidDoubleQuotedEscape")
	extractHighlight("NvimInvalidDoubleQuotedUnknownEscape")
	extractHighlight("NvimInvalidFigureBrace")
	extractHighlight("NvimInvalidSpacing")
	extractHighlight("NvimDoubleQuotedUnknownEscape")
	extractHighlight("WhidHeader")
	extractHighlight("WhidSubHeader")
	extractHighlight("AlphaHeader")
	extractHighlight("AlphaButtons")
	extractHighlight("SignDelete")
	extractHighlight("GitSignsAdd")
	extractHighlight("GitSignsChange")
	extractHighlight("GitSignsDelete")
	extractHighlight("SignAdd")
	extractHighlight("SignChange")
	extractHighlight("HopNextKey")
	extractHighlight("HopNextKey1")
	extractHighlight("HopNextKey2")
	extractHighlight("HopUnmatched")
	extractHighlight("VisualNOS")
	extractHighlight("MatchWord")
	extractHighlight("MatchWordCur")
	extractHighlight("MatchParenCur")
	extractHighlight("CursorIM")
	extractHighlight("Variable")
	extractHighlight("Bold")
	extractHighlight("Italic")
	extractHighlight("FloatBoder")
	extractHighlight("LazyReasonEvent")
	extractHighlight("LazyReasonFt")
	extractHighlight("LazyReasonImport")
	extractHighlight("LazyReasonKeys")
	extractHighlight("LazyReasonPlugin")
	extractHighlight("LazyReasonRuntime")
	extractHighlight("LazyReasonSource")
	extractHighlight("LazyReasonStart")
	extractHighlight("LazySpecial")
	extractHighlight("LazyTaskError")
	extractHighlight("LazyTaskOutput")
	extractHighlight("LazyUrl")
	extractHighlight("LazyValue")
	extractHighlight("LazyButton")
	extractHighlight("LazyButtonActive")
	extractHighlight("LazyComment")
	extractHighlight("LazyCommit")
	extractHighlight("LazyCommitIssue")
	extractHighlight("LazyCommitScope")
	extractHighlight("LazyCommitType")
	extractHighlight("LazyDir")
	extractHighlight("LazyH1")
	extractHighlight("LazyH2")
	extractHighlight("LazyNoCond")
	extractHighlight("LazyNormal")
	extractHighlight("LazyProgressDone")
	extractHighlight("LazyProgressTodo")
	extractHighlight("LazyProp")
	extractHighlight("LazyReasonCmd")
	extractHighlight("LirEmptyDirText")
	extractHighlight("LirFloatNormal")
	extractHighlight("LirDir")
	extractHighlight("LirSymLink")
	extractHighlight("LspReferenceRead")
	extractHighlight("LspReferenceText")
	extractHighlight("LspReferenceWrite")
	extractHighlight("LspSignatureActiveParameter")
	extractHighlight("LspCodeLens")
	extractHighlight("markdownCodeBlock")
	extractHighlight("markdownCodeDelimiter")
	extractHighlight("markdownH1")
	extractHighlight("markdownH2")
	extractHighlight("markdownH3")
	extractHighlight("markdownH4")
	extractHighlight("markdownH5")
	extractHighlight("markdownH6")
	extractHighlight("markdownHeadingDelimiter")
	extractHighlight("markdownHeadingRule")
	extractHighlight("markdownId")
	extractHighlight("markdownIdDeclaration")
	extractHighlight("markdownIdDelimiter")
	extractHighlight("markdownLinkDelimiter")
	extractHighlight("markdownItalic")
	extractHighlight("markdownLinkText")
	extractHighlight("markdownListMarker")
	extractHighlight("markdownOrderedListMarker")
	extractHighlight("markdownRule")
	extractHighlight("markdownUrl")
	extractHighlight("markdownBlockquote")
	extractHighlight("markdownBold")
	extractHighlight("markdownCode")
	extractHighlight("NeogitDiffDeleteHighlight")
	extractHighlight("NeogitDiffpaletteontextHighlight")
	extractHighlight("NeogitHunkHeader")
	extractHighlight("NeogitHunkHeaderHighlight")
	extractHighlight("NeogitDiffAdd")
	extractHighlight("NeogitDiffDelete")
	extractHighlight("NeogitNotificationInfo")
	extractHighlight("NeogitNotificationWarning")
	extractHighlight("NeogitNotificationError")
	extractHighlight("NeogitDiffAddHighlight")
	extractHighlight("NvimTreeLspDiagnosticsErr")
	extractHighlight("NvimTreeLspDiagnosticsError")
	extractHighlight("NvimTreeLspDiagnosticsHint")
	extractHighlight("NvimTreeLspDiagnosticsInformation")
	extractHighlight("NvimTreeLspDiagnosticsWarning")
	extractHighlight("NvimTreeGitStaged")
	extractHighlight("NvimTreeGitignoreIcon")
	extractHighlight("NvimTreeCursorLine")
	extractHighlight("NvimTreeEndOfBuffer")
	extractHighlight("NvimTreeSpecialFile")
	extractHighlight("NvimTreeGitIgnored")
	extractHighlight("NvimTreeIndentMarker")
	extractHighlight("NvimTreeFolderIcon")
	extractHighlight("NvimTreeImageFile")
	extractHighlight("NvimTreeNormal")
	extractHighlight("NvimTreeVertSplit")
	extractHighlight("NvimTreeFolderName")
	extractHighlight("NvimTreeOpenedFolderName")
	extractHighlight("NvimTreeEmptyFolderName")
	extractHighlight("NvimTreeGitNew")
	extractHighlight("NvimTreeGitRenamed")
	extractHighlight("NvimTreeGitDeleted")
	extractHighlight("NvimTreeGitMerge")
	extractHighlight("NvimTreeGitDirty")
	extractHighlight("NvimTreeSymlink")
	extractHighlight("NvimTreeRootFolder")
	extractHighlight("NvimTreeExecFile")
	extractHighlight("NvimTreeStatusLine")
	extractHighlight("NvimTreeStatusLineNC")
	extractHighlight("NvimTreeStatusNC")
	extractHighlight("CmpItemAbbrMatchFuzzy")
	extractHighlight("CmpItemMenu")
	extractHighlight("CmpItemKind")
	extractHighlight("CmpItemAbbr")
	extractHighlight("CmpItemAbbrDeprecated")
	extractHighlight("CmpItemAbbrMatch")
	extractHighlight("StatusLineSeparator")
	extractHighlight("StatusLineTerm")
	extractHighlight("StatusLineTermNC")
	extractHighlight("TelescopeNormal")
	extractHighlight("TelescopeSelection")
	extractHighlight("TelescopeMatching")
	extractHighlight("TelescopeBorder")
	extractHighlight("@const")
	extractHighlight("@const.builtin")
	extractHighlight("@error")
	extractHighlight("@const.macro")
	extractHighlight("@variable.builtin")
	extractHighlight("@parameter.reference")
	extractHighlight("@symbol")
	extractHighlight("@punctuation.delimiter")
	extractHighlight("@tag.delimiter")
	extractHighlight("@string.regex")
	extractHighlight("@emphasis")
	extractHighlight("@underline")
	extractHighlight("@title")
	extractHighlight("@literal")
	extractHighlight("@uri")
	extractHighlight("@keyword.operator")
	extractHighlight("@structure")
	extractHighlight("@strong")
	extractHighlight("@query")
	extractHighlight("@query.linter.error")
	extractHighlight("@punctuation.special")
	extractHighlight("@punctuation.bracket")
	extractHighlight("@annotation")
	extractHighlight("@attribute")
	extractHighlight("@type.builtin")
	extractHighlight("@keyword.function")
	extractHighlight("WhichKeyGroup")
	extractHighlight("WhichKeyDesc")
	extractHighlight("WhichKeyFloat")
	extractHighlight("WhichKey")
	extractHighlight("WhichKeySeperator")
	extractHighlight("TreesitterContext")
	extractHighlight("TreesitterContextLineNumber")
	extractHighlight("TreesitterContextBottom")
	extractHighlight("NONE")
	extractHighlight("TSPlaygroundFocus")
	extractHighlight("TSPlaygroundLang")
	extractHighlight("TSQueryLinterError")
	extractHighlight("rainbowcol1")
	extractHighlight("rainbowcol2")
	extractHighlight("rainbowcol3")
	extractHighlight("rainbowcol4")
	extractHighlight("rainbowcol5")
	extractHighlight("rainbowcol6")
	extractHighlight("rainbowcol7")
	extractHighlight("LspInfoFiletype")
	extractHighlight("LspInfoTitle")
	extractHighlight("LspInfoTip")
	extractHighlight("LspInfoList")
	extractHighlight("LspInfoBorder")
	extractHighlight("NullLsInfoBorder")
	extractHighlight("NullLsInfoSources")
	extractHighlight("NullLsInfoTitle")
	extractHighlight("NullLsInfoHeader")
	extractHighlight("CmpItemAbbrDefault")
	extractHighlight("CmpItemAbbrDeprecatedDefault")
	extractHighlight("CmpItemAbbrMatchDefault")
	extractHighlight("CmpItemAbbrMatchFuzzyDefault")
	extractHighlight("CmpItemKindDefault")
	extractHighlight("CmpItemMenuDefault")
	extractHighlight("CmpItemKindOperator")
	extractHighlight("CmpItemKindOperatorDefault")
	extractHighlight("CmpItemKindTypeParameter")
	extractHighlight("CmpItemKindTypeParameterDefault")
	extractHighlight("CmpItemKindEvent")
	extractHighlight("CmpItemKindEventDefault")
	extractHighlight("CmpItemKindStruct")
	extractHighlight("CmpItemKindStructDefault")
	extractHighlight("CmpItemKindEnumMember")
	extractHighlight("CmpItemKindEnumMemberDefault")
	extractHighlight("CmpItemKindConstant")
	extractHighlight("CmpItemKindConstantDefault")
	extractHighlight("CmpItemKindText")
	extractHighlight("CmpItemKindTextDefault")
	extractHighlight("CmpItemKindVariable")
	extractHighlight("CmpItemKindVariableDefault")
	extractHighlight("CmpItemKindFile")
	extractHighlight("CmpItemKindFileDefault")
	extractHighlight("CmpItemKindColor")
	extractHighlight("CmpItemKindColorDefault")
	extractHighlight("CmpItemKindValue")
	extractHighlight("CmpItemKindValueDefault")
	extractHighlight("CmpItemKindUnit")
	extractHighlight("CmpItemKindUnitDefault")
	extractHighlight("CmpItemKindFolder")
	extractHighlight("CmpItemKindFolderDefault")
	extractHighlight("CmpItemKindReference")
	extractHighlight("CmpItemKindReferenceDefault")
	extractHighlight("CmpItemKindKeyword")
	extractHighlight("CmpItemKindKeywordDefault")
	extractHighlight("CmpItemKindEnum")
	extractHighlight("CmpItemKindEnumDefault")
	extractHighlight("CmpItemKindMethod")
	extractHighlight("CmpItemKindMethodDefault")
	extractHighlight("CmpItemKindProperty")
	extractHighlight("CmpItemKindPropertyDefault")
	extractHighlight("CmpItemKindSnippet")
	extractHighlight("CmpItemKindSnippetDefault")
	extractHighlight("CmpItemKindModule")
	extractHighlight("CmpItemKindModuleDefault")
	extractHighlight("CmpItemKindInterface")
	extractHighlight("CmpItemKindInterfaceDefault")
	extractHighlight("CmpItemKindClass")
	extractHighlight("CmpItemKindClassDefault")
	extractHighlight("CmpItemKindField")
	extractHighlight("CmpItemKindFieldDefault")
	extractHighlight("CmpItemKindConstructor")
	extractHighlight("CmpItemKindConstructorDefault")
	extractHighlight("CmpItemKindFunction")
	extractHighlight("CmpItemKindFunctionDefault")
	extractHighlight("TelescopeResultsNormal")
	extractHighlight("TelescopePromptNormal")
	extractHighlight("TelescopePreviewUser")
	extractHighlight("TelescopePreviewSize")
	extractHighlight("TelescopeMultiIcon")
	extractHighlight("TelescopeMultiSelection")
	extractHighlight("TelescopeSelectionCaret")
	extractHighlight("TelescopeResultsDiffUntracked")
	extractHighlight("TelescopeResultsDiffDelete")
	extractHighlight("TelescopeResultsDiffAdd")
	extractHighlight("TelescopeResultsDiffChange")
	extractHighlight("TelescopeResultsSpecialComment")
	extractHighlight("TelescopeResultsComment")
	extractHighlight("TelescopeResultsNumber")
	extractHighlight("TelescopeResultsIdentifier")
	extractHighlight("TelescopeResultsLineNr")
	extractHighlight("TelescopeResultsVariable")
	extractHighlight("TelescopeResultsStruct")
	extractHighlight("Struct")
	extractHighlight("TelescopeResultsOperator")
	extractHighlight("TelescopeResultsMethod")
	extractHighlight("Method")
	extractHighlight("TelescopeResultsFunction")
	extractHighlight("TelescopeResultsField")
	extractHighlight("TelescopeResultsConstant")
	extractHighlight("TelescopeResultsClass")
	extractHighlight("TelescopePreviewMessageFillchar")
	extractHighlight("TelescopePreviewMessage")
	extractHighlight("TelescopePreviewNormal")
	extractHighlight("TelescopePreviewDate")
	extractHighlight("TelescopePreviewGroup")
	extractHighlight("TelescopePreviewSticky")
	extractHighlight("TelescopePreviewHyphen")
	extractHighlight("TelescopePreviewExecute")
	extractHighlight("TelescopePreviewWrite")
	extractHighlight("TelescopePreviewRead")
	extractHighlight("TelescopePreviewSocket")
	extractHighlight("TelescopePreviewLink")
	extractHighlight("TelescopePreviewBlock")
	extractHighlight("TelescopePreviewDirectory")
	extractHighlight("TelescopePreviewCharDev")
	extractHighlight("TelescopePreviewPipe")
	extractHighlight("TelescopePreviewMatch")
	extractHighlight("TelescopePreviewLine")
	extractHighlight("TelescopePromptPrefix")
	extractHighlight("TelescopePromptCounter")
	extractHighlight("TelescopePreviewTitle")
	extractHighlight("TelescopeTitle")
	extractHighlight("TelescopeResultsTitle")
	extractHighlight("TelescopePromptTitle")
	extractHighlight("TelescopePreviewBorder")
	extractHighlight("TelescopeResultsBorder")
	extractHighlight("TelescopePromptBorder")
	extractHighlight("IlluminatedWordText")
	extractHighlight("IlluminatedWordRead")
	extractHighlight("IlluminatedWordWrite")
	extractHighlight("DirvishSuffix")
	extractHighlight("DirvishPathTail")
	extractHighlight("DirvishArg")
	extractHighlight("BufferAlternate")
	extractHighlight("BufferDefaultAlternate")
	extractHighlight("BufferAlternateERROR")
	extractHighlight("BufferDefaultAlternateERROR")
	extractHighlight("BufferAlternateHINT")
	extractHighlight("BufferDefaultAlternateHINT")
	extractHighlight("BufferAlternateIcon")
	extractHighlight("BufferDefaultAlternateIcon")
	extractHighlight("BufferAlternateIndex")
	extractHighlight("BufferDefaultAlternateIndex")
	extractHighlight("BufferAlternateINFO")
	extractHighlight("BufferDefaultAlternateINFO")
	extractHighlight("BufferAlternateMod")
	extractHighlight("BufferDefaultAlternateMod")
	extractHighlight("BufferAlternateSign")
	extractHighlight("BufferDefaultAlternateSign")
	extractHighlight("BufferAlternateTarget")
	extractHighlight("BufferDefaultAlternateTarget")
	extractHighlight("BufferAlternateWARN")
	extractHighlight("BufferDefaultAlternateWARN")
	extractHighlight("BufferCurrent")
	extractHighlight("BufferDefaultCurrent")
	extractHighlight("BufferCurrentERROR")
	extractHighlight("BufferDefaultCurrentERROR")
	extractHighlight("BufferCurrentHINT")
	extractHighlight("BufferDefaultCurrentHINT")
	extractHighlight("BufferCurrentIcon")
	extractHighlight("BufferDefaultCurrentIcon")
	extractHighlight("BufferCurrentIndex")
	extractHighlight("BufferDefaultCurrentIndex")
	extractHighlight("BufferCurrentINFO")
	extractHighlight("BufferDefaultCurrentINFO")
	extractHighlight("BufferCurrentMod")
	extractHighlight("BufferDefaultCurrentMod")
	extractHighlight("BufferCurrentSign")
	extractHighlight("BufferDefaultCurrentSign")
	extractHighlight("BufferCurrentTarget")
	extractHighlight("BufferDefaultCurrentTarget")
	extractHighlight("BufferCurrentWARN")
	extractHighlight("BufferDefaultCurrentWARN")
	extractHighlight("BufferInactive")
	extractHighlight("BufferDefaultInactive")
	extractHighlight("BufferInactiveERROR")
	extractHighlight("BufferDefaultInactiveERROR")
	extractHighlight("BufferInactiveHINT")
	extractHighlight("BufferDefaultInactiveHINT")
	extractHighlight("BufferInactiveIcon")
	extractHighlight("BufferDefaultInactiveIcon")
	extractHighlight("BufferInactiveIndex")
	extractHighlight("BufferDefaultInactiveIndex")
	extractHighlight("BufferInactiveINFO")
	extractHighlight("BufferDefaultInactiveINFO")
	extractHighlight("BufferInactiveMod")
	extractHighlight("BufferDefaultInactiveMod")
	extractHighlight("BufferInactiveSign")
	extractHighlight("BufferDefaultInactiveSign")
	extractHighlight("BufferInactiveTarget")
	extractHighlight("BufferDefaultInactiveTarget")
	extractHighlight("BufferInactiveWARN")
	extractHighlight("BufferDefaultInactiveWARN")
	extractHighlight("BufferOffset")
	extractHighlight("BufferTabpageFill")
	extractHighlight("BufferDefaultTabpageFill")
	extractHighlight("BufferTabpages")
	extractHighlight("BufferDefaultTabpages")
	extractHighlight("BufferVisible")
	extractHighlight("BufferDefaultVisible")
	extractHighlight("BufferVisibleERROR")
	extractHighlight("BufferDefaultVisibleERROR")
	extractHighlight("BufferVisibleHINT")
	extractHighlight("BufferDefaultVisibleHINT")
	extractHighlight("BufferVisibleIcon")
	extractHighlight("BufferDefaultVisibleIcon")
	extractHighlight("BufferVisibleIndex")
	extractHighlight("BufferDefaultVisibleIndex")
	extractHighlight("BufferVisibleINFO")
	extractHighlight("BufferDefaultVisibleINFO")
	extractHighlight("BufferVisibleMod")
	extractHighlight("BufferDefaultVisibleMod")
	extractHighlight("BufferVisibleSign")
	extractHighlight("BufferDefaultVisibleSign")
	extractHighlight("BufferVisibleTarget")
	extractHighlight("BufferDefaultVisibleTarget")
	extractHighlight("BufferVisibleWARN")
	extractHighlight("BufferDefaultVisibleWARN")
	extractHighlight("BufferDefaultOffset")
	extractHighlight("debugPC")
	extractHighlight("DiffviewDiffAddAsDelete")
	extractHighlight("DiffviewDiffDelete")
	extractHighlight("DiffviewSecondary")
	extractHighlight("DiffviewPrimary")
	extractHighlight("DiffviewDim1")
	extractHighlight("DiffviewFilePanelFileName")
	extractHighlight("DiffviewFilePanelCounter")
	extractHighlight("DiffviewFilePanelTitle")
	extractHighlight("DiffviewWinSeparator")
	extractHighlight("DiffviewFilePanelRootPath")
	extractHighlight("DiffviewCursorLine")
	extractHighlight("DiffviewEndOfBuffer")
	extractHighlight("DiffviewNonText")
	extractHighlight("DiffviewStatusAdded")
	extractHighlight("diffAdded")
	extractHighlight("DiffviewFolderSign")
	extractHighlight("DiffviewFolderName")
	extractHighlight("DiffviewFilePanelConflicts")
	extractHighlight("DiffviewStatusUnmerged")
	extractHighlight("diffChanged")
	extractHighlight("DiffviewFilePanelDeletions")
	extractHighlight("diffRemoved")
	extractHighlight("DiffviewSignColumn")
	extractHighlight("DiffviewStatusTypeChange")
	extractHighlight("DiffviewStatusBroken")
	extractHighlight("DiffviewStatusCopied")
	extractHighlight("DiffviewFilePanelPath")
	extractHighlight("DiffviewReference")
	extractHighlight("DiffviewNormal")
	extractHighlight("DiffviewStatusUnknown")
	extractHighlight("DiffviewStatusUntracked")
	extractHighlight("DiffviewStatusModified")
	extractHighlight("DiffviewFilePanelInsertions")
	extractHighlight("DiffviewStatusLineNC")
	extractHighlight("DiffviewFilePanelSelected")
	extractHighlight("DiffviewStatusRenamed")
	extractHighlight("DiffviewStatusLine")
	extractHighlight("DiffviewStatusIgnored")
	extractHighlight("DiffviewStatusDeleted")
	extractHighlight("GitSignsUntracked")
	extractHighlight("GitSignsChangedelete")
	extractHighlight("GitSignsTopdelete")
	extractHighlight("GitSignsAddNr")
	extractHighlight("GitSignsChangeNr")
	extractHighlight("GitSignsDeleteNr")
	extractHighlight("GitSignsChangedeleteNr")
	extractHighlight("GitSignsTopdeleteNr")
	extractHighlight("GitSignsUntrackedNr")
	extractHighlight("GitSignsAddLn")
	extractHighlight("GitSignsChangeLn")
	extractHighlight("GitSignsChangedeleteLn")
	extractHighlight("GitSignsUntrackedLn")
	extractHighlight("GitSignsStagedAdd")
	extractHighlight("GitSignsStagedChange")
	extractHighlight("GitSignsStagedDelete")
	extractHighlight("GitSignsStagedChangedelete")
	extractHighlight("GitSignsStagedTopdelete")
	extractHighlight("GitSignsStagedAddNr")
	extractHighlight("GitSignsStagedChangeNr")
	extractHighlight("GitSignsStagedDeleteNr")
	extractHighlight("GitSignsStagedChangedeleteNr")
	extractHighlight("GitSignsStagedTopdeleteNr")
	extractHighlight("GitSignsStagedAddLn")
	extractHighlight("GitSignsStagedChangeLn")
	extractHighlight("GitSignsStagedChangedeleteLn")
	extractHighlight("GitSignsAddPreview")
	extractHighlight("GitSignsDeletePreview")
	extractHighlight("GitSignsCurrentLineBlame")
	extractHighlight("GitSignsAddInline")
	extractHighlight("GitSignsDeleteInline")
	extractHighlight("GitSignsChangeInline")
	extractHighlight("GitSignsAddLnInline")
	extractHighlight("GitSignsChangeLnInline")
	extractHighlight("GitSignsDeleteLnInline")
	extractHighlight("GitSignsDeleteVirtLn")
	extractHighlight("GitSignsDeleteVirtLnInLine")
	extractHighlight("HopCursor")
	extractHighlight("HopPreview")
	extractHighlight("UfoFoldedBg")
	extractHighlight("UfoFoldedFg")
	extractHighlight("UfoPreviewSbar")
	extractHighlight("UfoPreviewThumb")
	extractHighlight("UfoPreviewWinBar")
	extractHighlight("UfoPreviewCursorLine")
	extractHighlight("UfoFoldedEllipsis")
	extractHighlight("UfoCursorFoldedLine")
	extractHighlight("ScrollbarHandle")
	extractHighlight("ScrollbarInfo")
	extractHighlight("ScrollbarInfoHandle")
	extractHighlight("ScrollbarCursor")
	extractHighlight("ScrollbarCursorHandle")
	extractHighlight("ScrollbarGitChange")
	extractHighlight("ScrollbarGitChangeHandle")
	extractHighlight("ScrollbarGitAdd")
	extractHighlight("ScrollbarGitAddHandle")
	extractHighlight("ScrollbarMisc")
	extractHighlight("ScrollbarMiscHandle")
	extractHighlight("ScrollbarWarn")
	extractHighlight("ScrollbarWarnHandle")
	extractHighlight("ScrollbarError")
	extractHighlight("ScrollbarErrorHandle")
	extractHighlight("ScrollbarHint")
	extractHighlight("ScrollbarHintHandle")
	extractHighlight("ScrollbarSearch")
	extractHighlight("ScrollbarSearchHandle")
	extractHighlight("ScrollbarGitDelete")
	extractHighlight("ScrollbarGitDeleteHandle")
	extractHighlight("HlSearchNear")
	extractHighlight("HlSearchLens")
	extractHighlight("HlSearchLensNear")
	extractHighlight("Floaterm")
	extractHighlight("FloatermNC")
	extractHighlight("FloatermBorder")
	extractHighlight("ZenBg")
	extractHighlight("goCoverageCovered")
	extractHighlight("goCoverageUncovered")
	extractHighlight("goCoveragePartial")
	extractHighlight("LspCodeLensText")
	extractHighlight("LspCodeLensSign")
	extractHighlight("LspCodeLensSeparator")
end, {})
