#!/usr/bin/env bash

# ~/.config/polybar/launch.sh
#
if [ "$(bspc query -M --names | wc -l)" = 3 ]; then
  bspc monitor $(xrandr -q | grep '^eDP.*\bconnected' | awk '{print $1}') -d 1 2 3
  bspc monitor $(xrandr -q | grep '^DP.*\bconnected' | awk '{print $1}' | awk 'NR==1') -d 4 5 6
  bspc monitor $(xrandr -q | grep '^DP.*\bconnected' | awk '{print $1}' | awk 'NR==2') -d 7 8 9 
else
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width         1
bspc config window_gap          0
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# xprop | grep WM_CLASS
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config pointer_modifier mod4
bspc config pointer_action1 resize_corner # left click
bspc config pointer_action2 move # right click
bspc config pointer_action3 move

# bspc rule -a kakaotalk.exe border=off focus=off state=floating follow=off manage=off
# bspc rule -a KakaoTalk.exe border=off focus=off state=floating follow=off manage=off

bspc rule -a KakaoTalkEdgeWnd border=off follow=off state=floating follow=off manage=off
bspc rule -a KakaoTalkShadowWnd border=off follow=off state=floating follow=off manage=off


bspc rule -a kakaotalk.exe border=off  follow=off
bspc rule -a KakaoTalk.exe border=off follow=off
bspc rule -a explorer.exe border=off focus=off hidden=on
bspc rule -a motion_recorder border=off hidden=on focus=off

# pgrep grobi || nohup grobi watch -i 30 >/dev/null 2>&1&

# if ps -ef | grep grobi; then
#   :
# else
#   nohup ~/src/bin/tmp.sh >/dev/null 2>&1&
# end
