-- vim.cmd.packadd("image.nvim")
-- require("image").setup({
--   backend = "kitty",
--   integrations = {
--     markdown = {
--       enabled = true,
--       sizing_strategy = "auto",
--     },
--   },
--   max_width = nil,
--   max_height = nil,
--   max_width_window_percentage = nil,
--   max_height_window_percentage = 50,
--   kitty_method = "normal",
--   kitty_tmux_write_delay = 5,
-- })
