-- vim.cmd [[
-- packadd promise-async
-- packadd nvim-ufo
-- ]]
--
-- vim.keymap.set('n', 'zR', require('ufo').openAllFolds)
-- vim.keymap.set('n', 'zM', require('ufo').closeAllFolds)
--
-- require('ufo').setup({
--     provider_selector = function(bufnr, filetype, buftype)
--         return {'treesitter', 'indent'}
--     end
-- })
-- TODO: compare, use best
-- https://github.com/anuvyklack/pretty-fold.nvim
-- https://github.com/snelling-a/better-folds.nvim
