-- local _g = vim.g
-- _g.scrollview_on_startup = false
-- _g.scrollview_winblend = 80
-- _g.scrollview_base = "right"
--
-- vim.cmd([[
--   packadd nvim-scrollview
--   " ScrollViewEnable
--   autocmd CursorHold * if line('$') > 300 | ScrollViewEnable | endif
-- ]])
