-- vim.cmd.packadd("incline.nvim")
-- vim.cmd.packadd("nvim-web-devicons")
-- local helpers = require("incline.helpers")
-- local devicons = require("nvim-web-devicons")
-- require("incline").setup({
-- 	window = {
-- 		padding = 0,
-- 		margin = { horizontal = 0 },
--         zindex = 99,
-- 	},
--     hide = {
--         cursorline = true,
--     },
-- 	render = function(props)
-- 		local filename = vim.fn.fnamemodify(vim.api.nvim_buf_get_name(props.buf), ":t")
-- 		if filename == "" then
-- 			return {}
-- 		end
-- 		local ft_icon, ft_color = devicons.get_icon_color(filename)
-- 		local modified = vim.bo[props.buf].modified
-- 		return {
-- 			-- ft_icon and { ' ', ft_icon, ' ', guibg = ft_color, guifg = helpers.contrast_color(ft_color) } or '',
-- 			ft_icon and { " ", ft_icon, " " } or "",
-- 			-- "|",
-- 			{ filename, gui='italic' },
-- 			" ",
--             guibg = '#000000',
-- 		}
-- 	end,
-- })
--
