-- vim.cmd([[
-- 
--   autocmd TermLeave,InsertLeave,BufLeave zepl:* normal! G
-- let g:repl_config = { << EOF
--   'python': { 'cmd': 'ipython', 'formatter': function('zepl#contrib#python#formatter') } }
-- EOF
--   packadd zepl.vim
--   runtime zepl/contrib/python.vim  " Enable the Python contrib module.
--   runtime zepl/contrib/nvim_autoscroll_hack.vim
-- ]], false)

-- vim.cmd('buffers')
-- vim.cmd([[
-- let g:multiline =<< EOF
-- foo
-- bar
-- baz
-- EOF
-- ]])

-- vim.api.nvim_exec([[
-- command Foo << EOF
-- echo 'foo'
-- EOF
-- ]], false)
