live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x333333"
blue = "0x999999"
cyan = "0x444444"
green = "0x121212"
magenta = "0x999999"
red = "0xaaaaaa"
white = "0xc1c1c1"
yellow = "0x222222"

[colors.cursor]
cursor = "0xc1c1c1"
text = "0x000000"

[colors.normal]
black = "0x000000"
blue = "0x888888"
cyan = "0xaaaaaa"
green = "0xa5aaa7"
magenta = "0x999999"
red = "0x5f8787"
white = "0xc1c1c1"
yellow = "0x626b67"

[colors.primary]
background = "0x000000"
foreground = "0xc1c1c1"

[debug]
highlight_damage = false
log_level = "Off"
persistent_logging = false
print_events = false
render_timer = false

[env]
LC_CTYPE = "UTF-8"

[font]
builtin_box_drawing = true
size = 28

[font.bold]
family = "IosevkaTermSlab Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "IosevkaTermSlab Nerd Font"
style = "Oblique"

[font.normal]
family = "IosevkaTermSlab Nerd Font"
style = "ExtraLight"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = '[\S]{7,100}'

[hints.enabled.binding]
key = "G"
mods = "Alt"

# [hints.end]
# background = "0xffffff"
# foreground = "0x000000"
#
# [hints.start]
# background = "0xffffff"
# foreground = "0x000000"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3H"
key = "Home"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;3F"
key = "End"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mode = "Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;5~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[5;3~"
key = "PageUp"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mode = "Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;5~"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[6;3~"
key = "PageDown"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[2~"
key = "Insert"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal]
osc52 = "CopyPaste"

[window]
decorations = "none"
opacity = 1
# option_as_alt = "Both"

[window.padding]
x = 0
y = 0
