#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    swaylock \
        --screenshots \
        --clock \
        --indicator \
        --indicator-radius 100 \
        --indicator-thickness 7 \
        --effect-blur 7x5 \
        --effect-vignette 0.5:0.5 \
        --ring-color bb00cc \
        --key-hl-color 880033 \
        --line-color 00000000 \
        --inside-color 00000088 \
        --separator-color 00000000 \
        --fade-in 0.2

    # physlock
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # pmset displaysleepnow
    osascript -e 'tell application "System Events" to keystroke "q" using {command down,control down}' fi
fi
